const inventors = [
  { first: "Thomas", last: "Edison", year: 1847, passed: 1931 },
  { first: "Alexander", last: "Graham Bell", year: 1847, passed: 1922 },
  { first: "Nikola", last: "Tesla", year: 1856, passed: 1943 },
  { first: "Albert", last: "Einstein", year: 1879, passed: 1955 },
  { first: "Marie", last: "Curie", year: 1867, passed: 1934 },
  { first: "Steve", last: "Jobs", year: 1955, passed: 2011 },
  { first: "Elon", last: "Musk", year: 1971, passed: 2024 },
];

const names = [
  "John",
  "Emily",
  "Michael",
  "Jessica",
  "William",
  "Sophia",
  "Daniel",
  "Olivia",
  "Christopher",
  "Ava",
  "Matthew",
  "Emma",
  "David",
  "Isabella",
  "James",
  "Mia",
  "Joseph",
  "Charlotte",
  "Andrew",
  "Amelia",
  "Ryan",
  "Ethan",
  "Grace",
  "Alexander",
  "Harper",
  "Nicholas",
  "Evelyn",
  "Tyler",
  "Abigail",
  "Samuel",
  "Chloe",
  "Benjamin",
  "Elizabeth",
  "Brandon",
  "Ella",
  "Nathan",
  "Samantha",
  "Jonathan",
  "Victoria",
  "Christian",
  "Madison",
  "Dylan",
  "Avery",
  "Zachary",
  "Scarlett",
  "Logan",
  "Hannah",
  "Justin",
  "Lily",
  "Gabriel",
  "Addison",
  "Jose",
  "Natalie",
  "Brandon",
  "Lillian",
  "Kevin",
  "Zoe",
  "Austin",
  "Brooklyn",
  "Caleb",
  "Layla",
  "Robert",
  "Hailey",
  "Elijah",
  "Gabriella",
  "Thomas",
  "Kaylee",
  "Jordan",
  "Anna",
  "Jason",
  "Peyton",
  "Ian",
  "Leah",
  "Adam",
  "Audrey",
  "Isaac",
  "Aaliyah",
  "Mason",
  "Jasmine",
  "Juan",
  "Claire",
  "Bryan",
  "Morgan",
  "Evan",
  "Lucy",
  "Aiden",
  "Aria",
  "Carlos",
  "Katherine",
  "Cameron",
  "Julia",
  "Diego",
  "Alexandra",
  "Jayden",
  "Mackenzie",
  "Patrick",
  "Savannah",
];

// Array Prototype.filter()
// Filter the list of inventors who were born after 1900's to 1999's?

const filter = inventors.filter(function (inventor) {
  return ;
});

//Array Prototype.map()
// Give us an array of the inventory with first and last names?

// Array Prototype.sort()
// Sort the inventors by the birthdate, oldest to youngest?

// Array Prototype.reduce()
// How many years did all the inventors live?

// Sort the inventors by years lived
